### ISSUE TITLE
Cannot login: all credentials in the database do not match

### ISSUE THREAD

**Issue by indra87g** [samia13/Laravel-fullstack-blog#1]
how to fix it?

**Comment by Old3n** [comment]
i had this problem my self cuz i don't know much about PHP
this reason behind this problem is Laravel uses some hash algorithm to hash the password thats why u cant just copy and paste from the data base 
solution is to hash your own password and replace your hashed password with one in database 
just do these 5 easy steps 
1. Just open mysql and go to users table and choose one of the users who is already and admin 
2. then open command prompt at your project location and type  `php artisan tinker`
3. after you see something like "**Psy Shell v0.11.11 (PHP 8.3.7 — cli) by Justin Hileman**" type : `echo Hash::make('your_password');`
4. you can copy the result and paste in password field in database 
5. use ur email and password to login 
![solution](https://github.com/samia13/Laravel-fullstack-blog/assets/95956392/6ea4fe4c-0a43-4783-ae8e-388b892359c7)

**Comment by samia13** [comment]
> how to fix it?



> how to fix it?

Hello, 

i guess you forgot to run database seeder when you run "php artisan migrate", i am inserting a default user to the databse via these lines in seeders/DatabaseSeeder.php :

     // insert default user 
            DB::table('users')->insert([
                [
                    'name' => 'samia',
                    'email' => 'mahisamia13@gmail.com',
                    'password' => Hash::make('12345678'),
                    'role' =>   'admin',
                    'valid' => 1
                ]
            ]);
            
     you can change that to your default user

**Comment by indra87g** [comment]
thanks everyone, it works!
